/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import firstassignment.PersonProfile;
import java.awt.Color;
import java.io.File;
import java.lang.reflect.Field;
import javax.swing.JFileChooser;
import java.util.regex.Pattern;
import java.util.regex.Matcher;
import javax.swing.JOptionPane;

/**
 *
 * @author talre
 */
public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel
     */
    PersonProfile person;
    public CreatePanel() {
 
    }

    CreatePanel(PersonProfile person) {
        initComponents();
        this.person = person;
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        InputName = new javax.swing.JTextField();
        InputAddress = new javax.swing.JTextField();
        InputDoB = new javax.swing.JTextField();
        InputPhoneNumber = new javax.swing.JTextField();
        InputFaxNumber = new javax.swing.JTextField();
        InputEmailAddress = new javax.swing.JTextField();
        InputSSN = new javax.swing.JTextField();
        InputMedicalRecord = new javax.swing.JTextField();
        InputHealthPlan = new javax.swing.JTextField();
        InputBankAccount = new javax.swing.JTextField();
        InputCertificateNumber = new javax.swing.JTextField();
        InputVehicleId = new javax.swing.JTextField();
        InputDeviceId = new javax.swing.JTextField();
        InputLinkedin = new javax.swing.JTextField();
        InputIpAddress = new javax.swing.JTextField();
        InputUniqueId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel2.setBackground(new java.awt.Color(51, 153, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Create New Profile!");

        jLabel1.setText("Name:");

        jLabel3.setText("Address:");

        jLabel4.setText("DoB:");

        jLabel5.setText("Phone Number:");

        jLabel6.setText("Fax Number:");

        jLabel7.setText("Email Address:");

        jLabel8.setText("Social Security Number:");

        jLabel9.setText("Medical Record Number:");

        jLabel10.setText("Health Plan Number:");

        jLabel11.setText("Bank Account Number:");

        jLabel13.setText("Certificate Number:");

        jLabel14.setText("Vehicle Id Number:");

        jLabel15.setText("Device Id Number:");

        jLabel16.setText("LinkedIn Link:");

        jLabel17.setText("Ip Address:");

        jLabel18.setText("Photo Id:");

        jLabel19.setText("Unique Id:");

        InputName.setText("Enter Name!");
        InputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNameActionPerformed(evt);
            }
        });
        InputName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                InputNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                InputNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputNameKeyTyped(evt);
            }
        });

        InputAddress.setText("Enter Address!");
        InputAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputAddressActionPerformed(evt);
            }
        });

        InputDoB.setText("Enter DoB in MM/DD/YYY format");
        InputDoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputDoBActionPerformed(evt);
            }
        });

        InputPhoneNumber.setText("Enter Phone Number!");
        InputPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPhoneNumberActionPerformed(evt);
            }
        });

        InputFaxNumber.setText("Enter Fax Number");
        InputFaxNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputFaxNumberActionPerformed(evt);
            }
        });

        InputEmailAddress.setText("Enter email address");

        InputSSN.setText("Enter SSN number");

        InputMedicalRecord.setText("Enter MR Number");

        InputHealthPlan.setText("Enter Health Plan Number");

        InputBankAccount.setText("Enter 8 digit Bank account number");

        InputCertificateNumber.setText("Enter Covid Certificate number");
        InputCertificateNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputCertificateNumberActionPerformed(evt);
            }
        });

        InputVehicleId.setText("Enter Vehicle Number");
        InputVehicleId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputVehicleIdActionPerformed(evt);
            }
        });

        InputDeviceId.setText("Enter Device Id Number");
        InputDeviceId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputDeviceIdActionPerformed(evt);
            }
        });

        InputLinkedin.setText("Add Linkedin Link");

        InputIpAddress.setText("Add ip Address");

        InputUniqueId.setText("Add Unique identification marks, if any");

        jButton1.setText("Save Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Upload File");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(InputEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InputName, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InputAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InputDoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(InputFaxNumber))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(InputPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(InputHealthPlan)
                                    .addComponent(InputMedicalRecord)
                                    .addComponent(InputSSN)
                                    .addComponent(InputBankAccount, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(InputVehicleId))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(InputDeviceId))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InputLinkedin)
                                    .addComponent(InputIpAddress)
                                    .addComponent(InputUniqueId, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(InputCertificateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 150, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel13)
                    .addComponent(InputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputCertificateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel14)
                    .addComponent(InputAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputVehicleId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel15)
                    .addComponent(InputDoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputDeviceId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel16)
                    .addComponent(InputPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel17)
                    .addComponent(InputFaxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputIpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel18)
                    .addComponent(InputEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel19)
                    .addComponent(InputSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputUniqueId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(InputMedicalRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(InputHealthPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(InputBankAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void InputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNameActionPerformed

    private void InputAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputAddressActionPerformed

    private void InputDoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputDoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputDoBActionPerformed

    private void InputPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPhoneNumberActionPerformed

    private void InputFaxNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputFaxNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputFaxNumberActionPerformed

    private void InputCertificateNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputCertificateNumberActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_InputCertificateNumberActionPerformed

    private void InputVehicleIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputVehicleIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputVehicleIdActionPerformed

    private void InputDeviceIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputDeviceIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputDeviceIdActionPerformed
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int checker = 0;
        String reEmail = "^[a-zA-Z0-9_!#$%&’*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$";
        String reSSN = "^(?!666|000|9\\d{2})\\d{3}-(?!00)\\d{2}-(?!0{4})\\d{4}$";
        String reIp = "\\b\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\b";
        String reDob = "^(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)\\d\\d$";
        String rePhone = "^\\(?([0-9]{3})\\)?[-.●]?([0-9]{3})[-.●]?([0-9]{4})$";
        String reNumber = "^[0-9]{6,12}$";
        
        Pattern ptEmail = Pattern.compile(reEmail);
        Pattern ptSSN = Pattern.compile(reSSN);
        Pattern ptReIp = Pattern.compile(reIp);
        Pattern ptReDob = Pattern.compile(reDob);
        Pattern ptPhone = Pattern.compile(rePhone);
        Pattern ptReNumber = Pattern.compile(reNumber);
        
        Matcher mtEmail = ptEmail.matcher(InputEmailAddress.getText());
        Matcher mtSSN = ptSSN.matcher(InputSSN.getText());
        Matcher mtIp = ptReIp.matcher(InputIpAddress.getText());
        Matcher mtDob = ptReDob.matcher(InputDoB.getText());
        Matcher mtPhone = ptPhone.matcher(InputPhoneNumber.getText());
        Matcher mtFaxNumber = ptReNumber.matcher(InputFaxNumber.getText());
        
        if(mtEmail.matches() && !InputEmailAddress.equals("")){
            person.setEmailAddress(InputEmailAddress.getText());
            checker++;
        }
        else{
            InputEmailAddress.setBackground(Color.red);
            InputEmailAddress.setText("Enter Correct Email");
            
        }
        
        if(mtIp.matches() && !InputIpAddress.equals("")){
            person.setIpAddress(InputIpAddress.getText());
            checker++;
        }
        else{
            InputIpAddress.setBackground(Color.red);
            InputIpAddress.setText("Enter Correct Ip");
            
        }
        
        if(mtSSN.matches() && !InputSSN.equals("")){
            person.setSocialSecurityNumber(InputSSN.getText());
            checker++;
        }
        else{
        
            
        }
           
          if(mtDob.matches() && !InputDoB.equals("")){
              checker++;
            person.setDoB(InputDoB.getText());
        }
        else{
            InputDoB.setBackground(Color.red);
            InputDoB.setText("Enter Correct Date of Birth format mm/dd/yyyy");
            
        }
        
          if(mtPhone.matches() && !InputPhoneNumber.equals("")){
              checker++;
              person.setPhoneNumber(Long.parseLong(InputPhoneNumber.getText()));
          }
          else{
              InputPhoneNumber.setBackground(Color.red);
              InputPhoneNumber.setText("Enter correct Phone Number format");
          }
        if(mtFaxNumber.matches() && !InputFaxNumber.equals("")){
            checker++;
            person.setFaxNumber(Long.parseLong(InputFaxNumber.getText()));
        }
        else{
            InputFaxNumber.setBackground(Color.red);
            InputFaxNumber.setText("Etner correct Fax Number");
        }
        
        if(!InputName.equals("")){
            checker++;
        person.setFullName(InputName.getText());
    }else{
          InputName.setBackground(Color.red);
          InputName.setText("Name should not be empty");
            }
        
        
        person.setAddress(InputAddress.getText());
        person.setMedicalRecordNumber(Integer.parseInt(InputMedicalRecord.getText()));
        person.setHealthPlanNumber(Integer.parseInt(InputHealthPlan.getText()));
        person.setBankAccountNumber(Long.parseLong(InputBankAccount.getText()));
        person.setCertificateNumber(Integer.parseInt(InputCertificateNumber.getText()));
        person.setVehicleIdentifier(InputVehicleId.getText());
        person.setDeviceIdentifier(InputDeviceId.getText());
        person.setLinkedinLink(InputLinkedin.getText());
        person.setUniqueIdentification(InputUniqueId.getText());
        
      if(checker == 7){
          JOptionPane.showMessageDialog(null, "Info Saved");
      }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int response = fileChooser.showOpenDialog(null);
        if(response == JFileChooser.APPROVE_OPTION){
            File file = new File(fileChooser.getSelectedFile().getAbsolutePath());
            person.setPhotoFilePath(String.valueOf(file)); 
        }
        else{
            JOptionPane.showMessageDialog(null,"Photo Not added");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void InputNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputNameKeyTyped
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_InputNameKeyTyped

    private void InputNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputNameKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_InputNameKeyReleased

    private void InputNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputNameKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_InputNameKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputAddress;
    private javax.swing.JTextField InputBankAccount;
    private javax.swing.JTextField InputCertificateNumber;
    private javax.swing.JTextField InputDeviceId;
    private javax.swing.JTextField InputDoB;
    private javax.swing.JTextField InputEmailAddress;
    private javax.swing.JTextField InputFaxNumber;
    private javax.swing.JTextField InputHealthPlan;
    private javax.swing.JTextField InputIpAddress;
    private javax.swing.JTextField InputLinkedin;
    private javax.swing.JTextField InputMedicalRecord;
    private javax.swing.JTextField InputName;
    private javax.swing.JTextField InputPhoneNumber;
    private javax.swing.JTextField InputSSN;
    private javax.swing.JTextField InputUniqueId;
    private javax.swing.JTextField InputVehicleId;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
